name: Validate

on:
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        docker run --rm -v "${PWD}":/workdir mikefarah/yq eval-all . files/*
